version: "3"
services:
  db:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_USER: workout
      POSTGRES_PASSWORD: workout
      POSTGRES_DB: workout
    ports:
      - "5432:5432"
      